version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: mkdir
          command: mkdir store_test_results
      - run:
          name: Tests
          command: cp tests.xml store_test_results/tests.xml
      - run:
          name: Short
          command: cp short.xml store_test_results/short.xml
      - store_test_results:
          path: /tests.xml
      - store_test_results:
          path: /short.xml
          
      
