version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: mkdir
          command: mkdir store_test_results
      - run:
          name: Tests
          command: echo "1st"
      - run:
          name: Short
          command: echo "2nd"
      - store_test_results:
          path: ~
          
      
