version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: mkdir
          command: mkdir -p ~/phpunit
      - run:
          name: Tests
          command: cp tests.xml ~/phpunit/tests.xml
      - run:
          name: Short
          command: cp short.xml ~/phpunit/short.xml
      - store_test_results:
          path: ~/phpunit
          
      
