version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: mkdir
          command: mkdir -p /tmp/phpunit/reports
      - run:
          name: Short
          command: cp short.xml /tmp/phpunit/reports/junit.xml
      - store_test_results:
          path: /tmp/phpunit
          
      
